### ISSUE TITLE
Super search filter drop down not viewable

### ISSUE THREAD

**Issue by lucasmarcondes** [ASWWU-Web/frontend#48]
Seems to be an issue on Chrome for Windows

![image](https://user-images.githubusercontent.com/26172645/74489131-3119b880-4e79-11ea-91c9-c09621429039.png)

**Comment by nick97eagles** [comment]
Thanks @lucasmarcondes  I'll be looking into it today and hopefully rolling out a fix

**Comment by stephenermshar** [comment]
deployed under PR #56
