### ISSUE TITLE
Super search Llink broken when searching and no results found

### ISSUE THREAD

**Issue by kadensu** [ASWWU-Web/frontend#53]
**Describe the bug**
Link goes to https://aswwu.com/super-search instead of https://aswwu.com/mask/super-search

**To Reproduce**
1 - Search for something with no results, such as "sfasjdjfs"
2 - Click on the suggested link for super search

**Comment by stephenermshar** [comment]
This is the link in the results component that appears when there are no results for a search (?)

<img width="1277" alt="Screen Shot 2020-02-26 at 3 12 22 PM" src="https://user-images.githubusercontent.com/10591356/75396874-688d5980-58aa-11ea-8c34-24454c396781.png">

**Comment by nick97eagles** [comment]
Another "missing link" 👀
