### ISSUE TITLE
npm audit fix breaks functionality

### ISSUE THREAD

**Issue by nick97eagles** [ASWWU-Web/frontend#65]
## Issue
When running `npm audit fix` it changes the `@angular-devkit/build-angular` version. This somehow breaks the code and when `ng serve` is run this error is displayed:
```
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
```

**Comment by nick97eagles** [comment]
## Update
After a little bit of investigative work I have discovered that it has to do with the version of angular cli. I tried updating it but there are a bunch of dependencies that also need updating in order to follow through. So I tried updating those but then there were dependencies relating to those ones that needed updating as well. I quickly climbed out of the rabbit hole I found myself and decided that this is going to take some time.

**Comment by Mikhail-Beresnev** [comment]
Pull request #66 apparently fixed this issue
