### ISSUE TITLE
Search goes to undefined on mask

### ISSUE THREAD

**Issue by atg7000** [ASWWU-Web/frontend#99]
**Describe the bug**
If you go to ASWWU.com and search someone on the mask, the query field goes to undefined

**To Reproduce**
Go to ASWWU.com. Click on the search field for the mask, type a name in, and hit enter. The field should say undefined and the search bar should look like this "https://aswwu.com/mask/search?query=undefined"

**Expected behavior**
Instead of "undefined", it should be whatever you searched.

**Screenshots**
No screenshots

**Comment by octagonprogramming** [comment]
I am unable to replicate. What exactly were you searching

**Comment by octagonprogramming** [comment]
Or were you searching from homepage? When I search using the homepage I am able to replicate

**Comment by octagonprogramming** [comment]
Although it works when searching for someone who exists...

**Comment by Mikhail-Beresnev** [comment]
As we are currently unable to replicate the issue, it is going to be assumed that it is solved. If it pops up again, we can reopen this issue or create a new one
